### ISSUE TITLE
Taser fails to load CPHD X 0.3 files

### ISSUE THREAD

**Issue by mw-radar** [ngageoint/MATLAB_SAR#11]
### Issue
Attempting to open a CPHD X 0.3 file through the File->Open dialog of the main Taser GUI results in the following error:

> Reference to non-existent field 'CollectionInfo'.
>
>Error in Taser>LoadImage (line 324)  
>    if isfield(ph_reader,'read_cphd') && strcmpi(phdmeta.CollectionInfo.RadarMode.ModeType,'SPOTLIGHT')  
>
>Error in Taser>OpenMenuItem_Callback (line 288)
>handles = LoadImage(handles);
>
>Error in gui_mainfcn (line 95)
>        feval(varargin{:});
>
>Error in Taser (line 28)
>    gui_mainfcn(gui_State, varargin{:});
>
>Error in
matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)Taser('OpenMenuItem_Callback',hObject,eventdata,guidata(hObject)) 
>Error while evaluating Menu Callback.

### Cause

The _phdmeta_ structure returned at [line 323](https://github.com/ngageoint/MATLAB_SAR/blob/d69eaab47474e8dd49553b7f31391c1387d9914f/Tools/Taser/Taser.m#L323) contains a member called CollectionID, not CollectionInfo. This is created during the metadata update to the latest CPHD version (see [here](https://github.com/ngageoint/MATLAB_SAR/blob/d69eaab47474e8dd49553b7f31391c1387d9914f/IO/phase_history/cphd/cphd_update_meta_0_3.m#L50)) as part of the _open_ph_reader_ function.

### Suggested solution
Check for the presence of the _phdmeta.CollectionInfo_ or _phdmeta.CollectionID_ field and test for the ModeType accordingly. This would be similar to [this snippet](https://github.com/ngageoint/MATLAB_SAR/blob/d69eaab47474e8dd49553b7f31391c1387d9914f/Tools/SARLS/GetMetaData.m#L54-L56) in SARLS.

**Comment by utwade** [comment]
Actually, it should always be CollectionID.  CollectionInfo would be an error.  That fieldname is a remnant from before the current CPHD was an official standard and some assumptions were made in the code.  We are trying to remove any references to a CPHD CollectionInfo field; but some, like this one, may have slipped through.  If you adjust the merge request to look only for CollectionID, I will merge it.

For better or worse, this is an inconsistency between CPHD and SICD that was missed in initial approval of the standard.
