### ISSUE TITLE
How to ensure consistency in the results of multiple SNR calculation methods in the code RGIQE.m

### ISSUE THREAD

**Issue by ZHAOXuezhi666** [ngageoint/MATLAB_SAR#17]
I use the function ‘RGIQE.m’ in “MATLAB SAR Toolbox” and in this function, the signal level “S” and the noise level "sigma", there are several ways to calculate, here is my unclear point, how to ensure that the signal-to-noise ratio calculated by these ways is consistent, so that the results of equation (4) in the paper "Radar Generalized Image Quality Equation Applied to Capella Open Dataset"  are consistent?

**Comment by utwade** [comment]
Our recommended approach (and what we used in the paper your refer to, https://ieeexplore.ieee.org/document/9764201) is to always set S to 1.  That assures consistency when comparing various sensors and scenes, and the coefficients in the information metric-to-RNIIRS conversion were obtained from training on data that used that assumption.

The difficulty comes if data is not radiometrically calibrated.  Then any noise measurement isn't calibrated and thus can't really be compared to a calibrated assumed signal of 1.  In this case, you might be able to use some in-scene content that allows for a rough calibration, and the MATLAB function provide a few options to let you estimate it, but none of those is very precise.
