### ISSUE TITLE
Undefined function or variable

### ISSUE THREAD

**Issue by quruozhao** [ngageoint/MATLAB_SAR#3]
Hello， I want to use your code to process the satellite imagery of the sentinel radar, but in the process of running this program , the following error occurred.

**Undefined function or variable'SPEED_OF_LIGHT'.

 error： meta2sicd_s1product (line 120)
common_meta.Grid.Row.SS = (SPEED_OF_LIGHT/2) * delta_tau_s;**

I can't solve this problem through debugging. I hope to hear from you. 
Thank you very much.

**Comment by utwade** [comment]
Should be in MATLAB_SAR/Utilities/constants/

I would advise just adding the entire toolbox to your MATLAB path, and everything should work.

Let us know if you have any other issues.
